### PR TITLE
Update webpack.ts for NativeWind v4

### PR DESCRIPTION
**Pull request by panzacoder**
Added an option to pass in custom options for `babel/preset-react`, which is required in order to set the `importSource` for Nativewind v4.

I believe this is the root of these issues:
- https://github.com/marklawlor/nativewind/issues/659
- https://github.com/storybookjs/storybook/issues/24949

### CODE REVIEW

**Comment by panzacoder** [comment]
👋 You very much may want to solve this in a different way. After finding this I was able to equally solve the problem by updating my `babelPlugins` config like this:
```javascript
{
      name: getAbsolutePath('@storybook/addon-react-native-web'),
      options: {
        projectRoot,
        modulesToTranspile: [
          'app', // this is my local monorepo package
          'react-native',
          'react-native-web',
          'solito',
          'moti',
          'react-native-reanimated',
          'react-native-css-interop',
          'nativewind',
          'react-native-gesture-handler',
        ],
        babelPlugins: [
          'react-native-reanimated/plugin',
          [
            '@babel/plugin-transform-react-jsx',
            {
              runtime: 'automatic',
              importSource: 'nativewind',
            },
          ],
        ],
      },
    },
```

The key line being the change to the `@babel/plugin-transform-react-jsx`. I tried _MANY_ ways of configuring this for babel otherwise, but this is the only method that would work in order to make the transformation keep the NativeWind classNames intact.

**Comment by dannyhw** [comment]
@panzacoder I've updated this pr with some more changes to now allow babel presets and also to pass options to the react native preset

**Comment by dannyhw** [comment]
@panzacoder thats just adding it to the example so that its tested

**Comment by dannyhw** [comment]
@SocketSecurity ignore-all

**Pull request merged**
