### PR TITLE
Update to use updated babel preset package name in react native 73.

### PR DESCRIPTION
**Pull request by joarkosberg**
### Background

[React native 73 renamed the babel packages](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#babel-package-renames), which makes this addon not work with react native 73, as this package uses the old babel package name.

### Changes

*  Update to use updated babel preset package name in react native 73.
    *  Will then support react native 73, but not older versions.
*  Removed babel plugin `plugin-proposal-class-properties`, as react native already defines this
* Added babel dependency `plugin-proposal-export-namespace-from`, as it is not provided anymore.
* Updated dev react-native to 73 (including removing types which are part of react native now)
* Update README with new package name.

### CODE REVIEW

**Comment by dannyhw** [comment]
thanks so much for this contribution 🙏

**Comment by dannyhw** [comment]
heres the storybook https://618d44792e48fd003a482f88-wmaqsnknaj.chromatic.com/

**Review by dannyhw — APPROVED** [review]
Looks like it works great, thanks!

**Comment by dannyhw** [comment]
I think we could add some backwards compatibility here to toggle if we use the old or the new package name (another option maybe)

**Comment by joarkosberg** [comment]
> I think we could add some backwards compatibility here to toggle if we use the old or the new package name (another option maybe). I'll think of something for that then merge once I test that solution.


Sounds great 😊

**Comment by dannyhw** [comment]
just updated this so that it trys to use the new one if its installed and falls back to the old one if thats installed instead.

**Pull request merged**
