### PR TITLE
migrate to storybook 7.0.0-beta

### PR DESCRIPTION
**Pull request by natsuki-ornikar**
@dannyhw This is a draft, but I'm almost done doing the migration for 7.0 beta.
I'm stuck on this issue when starting Webpack 5:

```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /addon-react-native-web/storybook-config-entry.js:
Property object of MemberExpression expected node to be of a type ["Expression"] but instead got "Identifier"
````

Do you have any idea of what this can be? I admit I'm bit lost 🤔 

Ref issue: https://github.com/storybookjs/addon-react-native-web/issues/47

### CODE REVIEW

**Comment by dannyhw** [comment]
@natsuki-ornikar thats a weird error, I'll try ask around

**Comment by dannyhw** [comment]
my suspicion is that it might be related to this

Babel mode v7:

Storybook now uses [Babel mode v7](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7) exclusively. In 6.x, Storybook provided its own babel settings out of the box. Now, Storybook's uses your project's babel settings (.babelrc, babel.config.js, etc.) instead.

In the new mode, Storybook expects you to provide a configuration file. If you want a configuration file that's equivalent to the 6.x default, you can run the following command in your project directory:

`npx sb@next babelrc` 

maybe you can try running this command?

**Comment by natsuki-ornikar** [comment]
@dannyhw Still facing the same issue. 😞

Asking @yannbf from [storybookjs/addon-coverage](https://github.com/storybookjs/addon-coverage) if he had the same issue when migrating to 7.0 in https://github.com/storybookjs/addon-coverage/pull/3.

My suspicion is that is related to the Webpack rules options for `babel-loader` but I don't find something relevant.

**Comment by dannyhw** [comment]
Looks like its working now, the chromatic preview is here https://618d44792e48fd003a482f88-ziyaduhujd.chromatic.com/?path=/docs/introduction--docs

**Comment by dannyhw** [comment]
I'm going to merge this to a "next" branch where these changes can live until v7 is stable

**Comment by natsuki-ornikar** [comment]
Si this so great, thank you @dannyhw :-)

**Pull request merged**
